### ISSUE TITLE
Update styling updateProfile form with correct buttons classes

### ISSUE THREAD

**Issue by Simsteve7** [FundRequest/keycloak-build#3]
![image 2018-05-15 14 27 04](https://user-images.githubusercontent.com/1853096/40056553-0bbf5448-584c-11e8-80eb-a16a967ac38b.jpg)

![image 2018-05-15 14 08 50](https://user-images.githubusercontent.com/1853096/40055810-7ea97c98-5849-11e8-9293-e6a2966d90c6.jpg)

**Comment by fundrequest-notifier** [comment]
[![](https://dev-web.fundrequest.io/requests/56/badge)](https://dev-web.fundrequest.io/requests/56) [![](https://dev-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
This issue has been funded using [FundRequest](https://fundrequest.io). A developer can claim the reward by submitting a pull request referencing this issue. ([How to Close Issues via Pull Requests?](https://help.github.com/articles/closing-issues-using-keywords)) e.g. `fixes #3`

* For more help on how to claim on issue, please visit our [help section](https://help.fundrequest.io).
* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.

**Comment by karelstriegel** [comment]
blocked by https://github.com/FundRequest/platform/issues/445

**Comment by fundrequest-notifier** [comment]
[![](https://tst1-web.fundrequest.io/requests/65/badge)](https://tst1-web.fundrequest.io/requests/65) [![](https://tst1-web.fundrequest.io/assets/img/powered-by-fundrequest-badge.svg)](https://fundrequest.io)
Thank you @Simsteve7 for your code contribution. You can now claim [the reward](https://tst1-web.fundrequest.io/requests/65) that is linked to this issue. This can be done directly from the [funded request](https://tst1-web.fundrequest.io/requests/65).

* Looking for more? Feel free to [browse](https://fundrequest.io/requests) through all funded requests.
